server.port=8080
spring.application.name=neverfail-engine

spring.datasource.url=jdbc:postgresql://${DB_HOST:ep-shiny-recipe-ae5wr2g3.c-2.us-east-2.aws.neon.tech}:${DB_PORT:5432}/${DB_NAME:neondb}?sslmode=${DB_SSLMODE:require}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${DB_USER:neondb_owner}
spring.datasource.password=${DB_PASSWORD:npg_JUXGy67aAItn}

spring.threads.virtual.enabled=true
spring.sql.init.mode=always
